# Generated by Django 5.1.4 on 2025-07-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.IntegerField(default=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
